name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build image
      run: |
        ./build kvm-rootlessPodman-lima
    - uses: actions/upload-artifact@v4
      with:
        path: .build/kvm-rootlessPodman-lima*.qcow2
